[package]
name = "rustymesh-py"
version = "0.1.0"
edition = "2024"

[lib]
name = "rustymesh"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
rustymesh = { path = "../rustymesh", version = "0.1.0"}
