[package]
name = "rustymesh"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
aes = "0.8.4"
base64 = "0.22.1"
byteorder = "1.5.0"
ctr = "0.9.2"
meshtastic = {version = "0.1.8", features = ["gen"]}
